/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.custom.chat.services.service.model.impl;

import com.liferay.custom.chat.services.service.model.ChatUser;
import com.liferay.custom.chat.services.service.model.ChatUserModel;
import com.liferay.custom.chat.services.service.model.ChatUserSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ChatUser service. Represents a row in the &quot;CHAT_ChatUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ChatUserModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChatUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChatUserImpl
 * @generated
 */
@JSON(strict = true)
public class ChatUserModelImpl
	extends BaseModelImpl<ChatUser> implements ChatUserModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a chat user model instance should use the <code>ChatUser</code> interface instead.
	 */
	public static final String TABLE_NAME = "CHAT_ChatUser";

	public static final Object[][] TABLE_COLUMNS = {
		{"userId", Types.BIGINT}, {"fullName", Types.VARCHAR},
		{"avatar", Types.VARCHAR}, {"badge", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fullName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("avatar", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("badge", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CHAT_ChatUser (userId LONG not null primary key,fullName VARCHAR(75) null,avatar VARCHAR(75) null,badge INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table CHAT_ChatUser";

	public static final String ORDER_BY_JPQL = " ORDER BY chatUser.userId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CHAT_ChatUser.userId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static ChatUser toModel(ChatUserSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ChatUser model = new ChatUserImpl();

		model.setUserId(soapModel.getUserId());
		model.setFullName(soapModel.getFullName());
		model.setAvatar(soapModel.getAvatar());
		model.setBadge(soapModel.getBadge());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<ChatUser> toModels(ChatUserSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ChatUser> models = new ArrayList<ChatUser>(soapModels.length);

		for (ChatUserSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ChatUserModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _userId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUserId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _userId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ChatUser.class;
	}

	@Override
	public String getModelClassName() {
		return ChatUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ChatUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ChatUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChatUser, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((ChatUser)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ChatUser, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ChatUser, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ChatUser)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ChatUser, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ChatUser, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ChatUser>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ChatUser.class.getClassLoader(), ChatUser.class,
			ModelWrapper.class);

		try {
			Constructor<ChatUser> constructor =
				(Constructor<ChatUser>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ChatUser, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ChatUser, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ChatUser, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ChatUser, Object>>();
		Map<String, BiConsumer<ChatUser, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ChatUser, ?>>();

		attributeGetterFunctions.put("userId", ChatUser::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<ChatUser, Long>)ChatUser::setUserId);
		attributeGetterFunctions.put("fullName", ChatUser::getFullName);
		attributeSetterBiConsumers.put(
			"fullName", (BiConsumer<ChatUser, String>)ChatUser::setFullName);
		attributeGetterFunctions.put("avatar", ChatUser::getAvatar);
		attributeSetterBiConsumers.put(
			"avatar", (BiConsumer<ChatUser, String>)ChatUser::setAvatar);
		attributeGetterFunctions.put("badge", ChatUser::getBadge);
		attributeSetterBiConsumers.put(
			"badge", (BiConsumer<ChatUser, Integer>)ChatUser::setBadge);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getFullName() {
		if (_fullName == null) {
			return "";
		}
		else {
			return _fullName;
		}
	}

	@Override
	public void setFullName(String fullName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fullName = fullName;
	}

	@JSON
	@Override
	public String getAvatar() {
		if (_avatar == null) {
			return "";
		}
		else {
			return _avatar;
		}
	}

	@Override
	public void setAvatar(String avatar) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_avatar = avatar;
	}

	@JSON
	@Override
	public int getBadge() {
		return _badge;
	}

	@Override
	public void setBadge(int badge) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_badge = badge;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ChatUser.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ChatUser toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ChatUser>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ChatUserImpl chatUserImpl = new ChatUserImpl();

		chatUserImpl.setUserId(getUserId());
		chatUserImpl.setFullName(getFullName());
		chatUserImpl.setAvatar(getAvatar());
		chatUserImpl.setBadge(getBadge());

		chatUserImpl.resetOriginalValues();

		return chatUserImpl;
	}

	@Override
	public ChatUser cloneWithOriginalValues() {
		ChatUserImpl chatUserImpl = new ChatUserImpl();

		chatUserImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		chatUserImpl.setFullName(
			this.<String>getColumnOriginalValue("fullName"));
		chatUserImpl.setAvatar(this.<String>getColumnOriginalValue("avatar"));
		chatUserImpl.setBadge(this.<Integer>getColumnOriginalValue("badge"));

		return chatUserImpl;
	}

	@Override
	public int compareTo(ChatUser chatUser) {
		long primaryKey = chatUser.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ChatUser)) {
			return false;
		}

		ChatUser chatUser = (ChatUser)object;

		long primaryKey = chatUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ChatUser> toCacheModel() {
		ChatUserCacheModel chatUserCacheModel = new ChatUserCacheModel();

		chatUserCacheModel.userId = getUserId();

		chatUserCacheModel.fullName = getFullName();

		String fullName = chatUserCacheModel.fullName;

		if ((fullName != null) && (fullName.length() == 0)) {
			chatUserCacheModel.fullName = null;
		}

		chatUserCacheModel.avatar = getAvatar();

		String avatar = chatUserCacheModel.avatar;

		if ((avatar != null) && (avatar.length() == 0)) {
			chatUserCacheModel.avatar = null;
		}

		chatUserCacheModel.badge = getBadge();

		return chatUserCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ChatUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ChatUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChatUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ChatUser)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ChatUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ChatUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChatUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ChatUser)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ChatUser>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _userId;
	private String _fullName;
	private String _avatar;
	private int _badge;

	public <T> T getColumnValue(String columnName) {
		Function<ChatUser, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ChatUser)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("fullName", _fullName);
		_columnOriginalValues.put("avatar", _avatar);
		_columnOriginalValues.put("badge", _badge);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("userId", 1L);

		columnBitmasks.put("fullName", 2L);

		columnBitmasks.put("avatar", 4L);

		columnBitmasks.put("badge", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ChatUser _escapedModel;

}