/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.custom.chat.services.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Message service. Represents a row in the &quot;CHAT_Message&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.custom.chat.services.service.model.impl.MessageModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.custom.chat.services.service.model.impl.MessageImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Message
 * @generated
 */
@ProviderType
public interface MessageModel
	extends BaseModel<Message>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a message model instance should use the {@link Message} interface instead.
	 */

	/**
	 * Returns the primary key of this message.
	 *
	 * @return the primary key of this message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this message.
	 *
	 * @param primaryKey the primary key of this message
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the message ID of this message.
	 *
	 * @return the message ID of this message
	 */
	public long getMessageId();

	/**
	 * Sets the message ID of this message.
	 *
	 * @param messageId the message ID of this message
	 */
	public void setMessageId(long messageId);

	/**
	 * Returns the group ID of this message.
	 *
	 * @return the group ID of this message
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this message.
	 *
	 * @param groupId the group ID of this message
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this message.
	 *
	 * @return the company ID of this message
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this message.
	 *
	 * @param companyId the company ID of this message
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this message.
	 *
	 * @return the user ID of this message
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this message.
	 *
	 * @param userId the user ID of this message
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this message.
	 *
	 * @return the user uuid of this message
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this message.
	 *
	 * @param userUuid the user uuid of this message
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this message.
	 *
	 * @return the user name of this message
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this message.
	 *
	 * @param userName the user name of this message
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this message.
	 *
	 * @return the create date of this message
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this message.
	 *
	 * @param createDate the create date of this message
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this message.
	 *
	 * @return the modified date of this message
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this message.
	 *
	 * @param modifiedDate the modified date of this message
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the to user ID of this message.
	 *
	 * @return the to user ID of this message
	 */
	public long getToUserId();

	/**
	 * Sets the to user ID of this message.
	 *
	 * @param toUserId the to user ID of this message
	 */
	public void setToUserId(long toUserId);

	/**
	 * Returns the to user uuid of this message.
	 *
	 * @return the to user uuid of this message
	 */
	public String getToUserUuid();

	/**
	 * Sets the to user uuid of this message.
	 *
	 * @param toUserUuid the to user uuid of this message
	 */
	public void setToUserUuid(String toUserUuid);

	/**
	 * Returns the from user ID of this message.
	 *
	 * @return the from user ID of this message
	 */
	public long getFromUserId();

	/**
	 * Sets the from user ID of this message.
	 *
	 * @param fromUserId the from user ID of this message
	 */
	public void setFromUserId(long fromUserId);

	/**
	 * Returns the from user uuid of this message.
	 *
	 * @return the from user uuid of this message
	 */
	public String getFromUserUuid();

	/**
	 * Sets the from user uuid of this message.
	 *
	 * @param fromUserUuid the from user uuid of this message
	 */
	public void setFromUserUuid(String fromUserUuid);

	/**
	 * Returns the message type of this message.
	 *
	 * @return the message type of this message
	 */
	@AutoEscape
	public String getMessageType();

	/**
	 * Sets the message type of this message.
	 *
	 * @param messageType the message type of this message
	 */
	public void setMessageType(String messageType);

	/**
	 * Returns the message text of this message.
	 *
	 * @return the message text of this message
	 */
	@AutoEscape
	public String getMessageText();

	/**
	 * Sets the message text of this message.
	 *
	 * @param messageText the message text of this message
	 */
	public void setMessageText(String messageText);

	@Override
	public Message cloneWithOriginalValues();

}